
  create table "public"."profiles" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "full_name" text,
    "email" text
      );


alter table "public"."profiles" enable row level security;


  create table "public"."sections" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "icon" text default '🦉'::text,
    "user_id" uuid not null
      );


alter table "public"."sections" enable row level security;


  create table "public"."sections_feeds" (
    "created_at" timestamp with time zone not null default now(),
    "section_id" bigint not null,
    "feed_id" bigint not null
      );


alter table "public"."sections_feeds" enable row level security;

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX sections_feeds_pkey ON public.sections_feeds USING btree (section_id, feed_id);

CREATE UNIQUE INDEX sections_pkey ON public.sections USING btree (id);

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."sections" add constraint "sections_pkey" PRIMARY KEY using index "sections_pkey";

alter table "public"."sections_feeds" add constraint "sections_feeds_pkey" PRIMARY KEY using index "sections_feeds_pkey";

alter table "public"."sections" add constraint "sections_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."sections" validate constraint "sections_user_id_fkey";

alter table "public"."sections_feeds" add constraint "sections_feeds_feed_id_fkey" FOREIGN KEY (feed_id) REFERENCES public.feeds(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."sections_feeds" validate constraint "sections_feeds_feed_id_fkey";

alter table "public"."sections_feeds" add constraint "sections_feeds_section_id_fkey" FOREIGN KEY (section_id) REFERENCES public.sections(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."sections_feeds" validate constraint "sections_feeds_section_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."sections" to "anon";

grant insert on table "public"."sections" to "anon";

grant references on table "public"."sections" to "anon";

grant select on table "public"."sections" to "anon";

grant trigger on table "public"."sections" to "anon";

grant truncate on table "public"."sections" to "anon";

grant update on table "public"."sections" to "anon";

grant delete on table "public"."sections" to "authenticated";

grant insert on table "public"."sections" to "authenticated";

grant references on table "public"."sections" to "authenticated";

grant select on table "public"."sections" to "authenticated";

grant trigger on table "public"."sections" to "authenticated";

grant truncate on table "public"."sections" to "authenticated";

grant update on table "public"."sections" to "authenticated";

grant delete on table "public"."sections" to "service_role";

grant insert on table "public"."sections" to "service_role";

grant references on table "public"."sections" to "service_role";

grant select on table "public"."sections" to "service_role";

grant trigger on table "public"."sections" to "service_role";

grant truncate on table "public"."sections" to "service_role";

grant update on table "public"."sections" to "service_role";

grant delete on table "public"."sections_feeds" to "anon";

grant insert on table "public"."sections_feeds" to "anon";

grant references on table "public"."sections_feeds" to "anon";

grant select on table "public"."sections_feeds" to "anon";

grant trigger on table "public"."sections_feeds" to "anon";

grant truncate on table "public"."sections_feeds" to "anon";

grant update on table "public"."sections_feeds" to "anon";

grant delete on table "public"."sections_feeds" to "authenticated";

grant insert on table "public"."sections_feeds" to "authenticated";

grant references on table "public"."sections_feeds" to "authenticated";

grant select on table "public"."sections_feeds" to "authenticated";

grant trigger on table "public"."sections_feeds" to "authenticated";

grant truncate on table "public"."sections_feeds" to "authenticated";

grant update on table "public"."sections_feeds" to "authenticated";

grant delete on table "public"."sections_feeds" to "service_role";

grant insert on table "public"."sections_feeds" to "service_role";

grant references on table "public"."sections_feeds" to "service_role";

grant select on table "public"."sections_feeds" to "service_role";

grant trigger on table "public"."sections_feeds" to "service_role";

grant truncate on table "public"."sections_feeds" to "service_role";

grant update on table "public"."sections_feeds" to "service_role";


